### ISSUE TITLE
Ask for rules for designing ui/ux

### ISSUE THREAD

**Issue by hey6** [hiriski/react-native-hoctiengviet#1]
Can you provide a guide for creating an ui ? what kind of library you will use to build interface, icons, typography etc.
![Screen Shot 2021-03-20 at 09 34 03](https://user-images.githubusercontent.com/75413025/111856733-70111c00-895f-11eb-8e18-8b1f0636b603.png)

**Comment by hiriski** [comment]
@hey6 thanks for creating an issue.
Actually we don't have rules to make an ux/ui, but to make hight quality app i have a few rules.

To make UI i've plan to use **React Native UIKitten**, read this documentation for more information [https://akveo.github.io/react-native-ui-kitten/docs](url).

### Typefaces font.
- Primary font : **HKGrotesk** [https://www.fontsquirrel.com/fonts/hk-grotesk](url)
- Secondary font : **Lora** [https://fonts.google.com/specimen/Lora?preview.text_type=custom](url)

### Icons
- Icons : Eva Icons [https://akveo.github.io/eva-icons/](url)

### Colors
- (Primary) #f33c5a 
- (Secondary) #003bff, #ffcd00, #00b15e
- (Primary text color)  #333333
- (Secondary text color) #7d7d7d

### Screens
1. Login
2. Register
3. Reset Password
4. ObBoardingScreen
5. Homescreen
6. AlphabetScreen
7. PhrasebookListScreen (all)
8. PhrasebookListScreen (By category)
9. PhrasebookCategoryListScreen
10. ProfileScreen
11. ProfileSettingScreen
12. DiscussionListScreen (Feed)
13. MemberListScreen (UserList)
14. UserDetailsScreen
15. GuideScreen
16. SongScreen
17. AboutScreen
18. SendFeedBackScreen
19. UserDetailsScreen
20. FavoriteScreen


Cảm ơn trang :)

**Comment by hey6** [comment]
Không có gì :)
Ok let me work on it.
